### ISSUE TITLE
Rename sexpr-wasm binaries

### ISSUE THREAD

**Issue by binji** [WebAssembly/sexpr-wasm-prototype#100]
@sbc100 mentioned that we should probably rename the binaries for clarity:

sexpr-wasm -> wast2wasm
wasm-wast -> wasm2wast

**Comment by sbc100** [comment]
We could leave symlinks around for a while I guess.

Also, the repo probably needs a new name too, but that can happen independently.

**Comment by citisolo** [comment]
#102

**Comment by binji** [comment]
Thanks for fixing this!
