### ISSUE TITLE
failed to parse file

### ISSUE THREAD

**Issue by wanderer** [WebAssembly/sexpr-wasm-prototype#12]
Failed to parse [this file](https://github.com/WebAssembly/wasm-to-llvm-prototype/blob/master/perf_tests/matrix/mul/mul.wast)

./test.wasm:[90:19: unexpected token "i32.div"](https://github.com/WebAssembly/wasm-to-llvm-prototype/blob/master/perf_tests/matrix/mul/mul.wast#L90)

If I change them all of the i32.div to i32.add it works fine

**Comment by jfbastien** [comment]
It's `div_s` or `div_u`, not `div`.

**Comment by wanderer** [comment]
cool thanks
