### ISSUE TITLE
br-block-named.txt is incorrect

### ISSUE THREAD

**Issue by kg** [WebAssembly/sexpr-wasm-prototype#13]
Specifically:

```
          (block $inner     ;; 0
            (br $inner)
            (br $outer)))))))
```

->

```
0000013: 01                                         ; OPCODE_BLOCK
0000014: 02                                         ; num expressions
0000015: 06                                         ; OPCODE_BR
0000016: 00                                         ; break depth
0000017: 00                                         ; OPCODE_NOP
0000018: 06                                         ; OPCODE_BR
0000019: 04                                         ; break depth
000001a: 00                                         ; OPCODE_NOP
```

The block has 2 child expressions but four expressions are emitted. When parsing this produces ```br 0``` followed by ```nop``` and then the function body has a trailing ```br 4```, ```nop``` which is not only an incorrect decoding but invalid (due to the break depth).

**Comment by kg** [comment]
A form of this also appears in br-loop-inner-expr but it's different - not every ```br``` produces a ```nop```. So even if this is intended, it is unclear how to parse it correctly.

**Comment by binji** [comment]
in v8-native binary format, the br operation is defined as always taking an expression value, so I believe this is correct. `(br <depth>)` just uses nop for the expression value, but in `br-loop-inner-expr` line 8 uses `(i32.const 4)` as the expression value so
```
      (if (i32.const 3)
        (br $exit (i32.const 4)))
```
is translated as
```
0000013: 03                                         ; OPCODE_IF
0000014: 09                                         ; OPCODE_I8_CONST
0000015: 03                                         ; u8 literal
0000016: 06                                         ; OPCODE_BR
0000017: 01                                         ; break depth
0000018: 09                                         ; OPCODE_I8_CONST
0000019: 04                                         ; u8 literal
```

**Comment by kg** [comment]
Why does br take a value? We should call this out in the design, because it is not stated. I do see it in ml-proto.

**Comment by binji** [comment]
It's referenced here: https://github.com/WebAssembly/design/blob/master/AstSemantics.md#branches-and-nesting
> Branches that exit a block, loop, or tableswitch may take a subexpression that yields a value for the exited construct.

**Comment by jcbeyler** [comment]
And you can find examples in the testsuite in labels.wast and switch.wast
