### ISSUE TITLE
sexpr-wasm can't commute align= offset=

### ISSUE THREAD

**Issue by jfbastien** [WebAssembly/sexpr-wasm-prototype#17]
Some of the torture tests fail with this because s2wasm emits them in the opposite order as wasmate, e.g.:
```
(f64.store align=1 offset=8 (i32.const 0) (f64.const 0))
```

It would be good to also update store-offset.txt adn load-offset.txt, as well as make sure that the spec repo has the same tests.

s2wasm_known_gcc_test_failures.txt has a list of expected failures. I don't run it on the bots yet (will add this afternoon), to repro:
```
/s/wasm/experimental/buildbot/assemble_files.py --assembler /s/wasm/experimental/buildbot/work/sexpr-wasm-prototype/out/sexpr-wasm --files /s/wasm/experimental/buildbot/work/s2wasm-out/\*.wast --fails /s/wasm/experimental/buildbot/work/sexpr-wasm-prototype/s2wasm_known_gcc_test_failures.txt --out /s/wasm/experimental/buildbot/work/sexpr-wasm-out/
```

**Comment by binji** [comment]
sexpr-wasm matches the spec repo. See https://github.com/WebAssembly/spec/blob/master/ml-proto/host/parser.mly#L252. Maybe s2wasm should emit them in the correct order. :smile:

**Comment by binji** [comment]
Closing, sounds like we've decided on having a fixed order.
