### ISSUE TITLE
br not accepting a nop?

### ISSUE THREAD

**Issue by JSStats** [WebAssembly/sexpr-wasm-prototype#20]
Seems odd that the v8 encoding requires a nop opcode as fill in br and br_if but sexpr-wasm-prototype will not accept a nop value in the same place?

uncompr.wast:109:11: arity mismatch of br_if value. label expects void, but br value is non-empty

**Comment by binji** [comment]
Seems strange, yes, but it matches the behavior of the spec interpreter:
```
$ cat test4.wast
(module
  (func
    (block $exit
      (br $exit (nop)))))
$ ./wasm  test4.wast
test4.wast:4.7-4.23: arity mismatch
```

**Comment by binji** [comment]
Closing for now. Let's reopen if the discussion on https://github.com/WebAssembly/design/issues/518 changes things.
