### ISSUE TITLE
FP parsing fail

### ISSUE THREAD

**Issue by jfbastien** [WebAssembly/sexpr-wasm-prototype#29]
The following FP number doesn't parse: `1.e+300`.
Error: `unexpected token "1.e+300"`

The problem is `.e` if I change it to `1.0e+300` it works.

**Comment by binji** [comment]
This also fails in the spec repo, I just copied the float lexer from there.

**Comment by jfbastien** [comment]
Looking at the C++ grammar:
```
floating-literal:
  fractional-constant exponent-part[opt] floating-suffix[opt]
  digit-sequence exponent-part floating-suffix[opt]
fractional-constant:
  digit-sequenceopt. digit-sequence
  digit-sequence .
exponent-part:
  e signopt digit-sequence
  E signopt digit-sequence
sign: one of
  + -
digit-sequence:
  digit
  digit-sequence digit
floating-suffix: one of
  f l F L
```
Whereas the IEEE-754 examples always have a the zero in `1.0e300`. I'm not sure which is right. C++ definitely allows `1.` as a valid constant, but that may be a convenience thing?

**Comment by binji** [comment]
Easy enough to support it, so might as well. Fixed in b8038680d76b081b5c8250b1f0ca711bcfaa1511.

**Comment by sunfishcode** [comment]
I don't have an opinion about which is best, but it would be good in general for parsers to abide by the same restrictions as the spec repo, or to remove the restrictions from the spec repo.

**Comment by jfbastien** [comment]
Agreed with @sunfishcode. @rossberg-chromium WDYT we should standardize on?
