### ISSUE TITLE
Multiple exports per function being accepted?

### ISSUE THREAD

**Issue by JSStats** [WebAssembly/sexpr-wasm-prototype#33]
The following test from the spec seems to conflict with the v8 encoding which can only have one export per function. Should sexp-wasm signal an error on this? Should the spec be changed to make this invalid?

```(module (func (i32.const 1)) (export "a" 0) (export "b" 0))```

**Comment by binji** [comment]
Good catch. I think I threw an error in the previous version of sexpr-wasm, but it looks like it just chooses the last exported name now.

**Comment by binji** [comment]
Filed: https://bugs.chromium.org/p/v8/issues/detail?id=4732

**Comment by lukewagner** [comment]
FWIW, this is handled in SM by exporting two functions that are given the same identity ([test](http://hg.mozilla.org/mozilla-central/file/f53533d9eb77/js/src/jit-test/tests/wasm/basic.js#l60)).

**Comment by binji** [comment]
This has long been supported w/ export tables.
