### ISSUE TITLE
Support start

### ISSUE THREAD

**Issue by jfbastien** [WebAssembly/sexpr-wasm-prototype#34]
As in: https://github.com/WebAssembly/design/pull/495

I'm adding support for it in: https://github.com/WebAssembly/binaryen/pull/182

**Comment by binji** [comment]
What is this expected to do? The v8 binary format doesn't have a start symbol, so I'm not sure what I'd generate for this.

**Comment by jfbastien** [comment]
It's the entrypoint that, if present, gets called automatically.

**Comment by titzer** [comment]
We probably need to have another section or add a function declaration flag.

**Comment by jfbastien** [comment]
@titzer by "another section" do you mean an expression under `(module ...)` called `(start ...)`? That's what the design has now. binaryen emits the following:
https://github.com/WebAssembly/binaryen/blob/master/test/dot_s/start_main2.wast

Do that look good? I can change it if not.

**Comment by binji** [comment]
Is the start function always nullary? It seems weird that you create two locals, but don't set them, then pass them to main.

**Comment by jfbastien** [comment]
Yes start is always nullary,

Eventually I'll set the argc / argv values passed to main (presumably by asking the embedder for values) but we're learning to walk right now: tests have main, we have to call something. It's either `--entry`, something hard-coded, or what's in the design repo already.

**Comment by binji** [comment]
Fixed in 580805a3f531173ecba67550a3584bfd3744df58.
