### ISSUE TITLE
Dirty repo

### ISSUE THREAD

**Issue by jfbastien** [WebAssembly/sexpr-wasm-prototype#35]
Updating sexpr-wasm in a pre-built repo causes the following error:
```
sexpr directory already exists
subprocess.check_call(`git fetch`, cwd=`/b/build/slave/linux/build/src/src/work/sexpr-wasm-prototype`)
subprocess.check_call(`git checkout origin/master`, cwd=`/b/build/slave/linux/build/src/src/work/sexpr-wasm-prototype`)
error: Your local changes to the following files would be overwritten by checkout:
	src/wasm-flex-lexer.c
Please, commit your changes or stash them before you can switch branches.
Aborting
```
Are in-tree builds expected to be clean?

**Comment by binji** [comment]
Hm, the version of flex you're using must be generating a different wasm-flex-lexer.c. I like having those generated files checked in, so you don't need flex/bison installed. But maybe I should be more clever in the build system about using pre-generated files.

**Comment by jfbastien** [comment]
That's from the waterfall :-)
I think it's on every change, the first time it happens. Subsequent ones
are OK.

**Comment by binji** [comment]
This should be fixed when I land the cmake branch: https://github.com/WebAssembly/sexpr-wasm-prototype/tree/cmake. Holding off for now, while we push through the other binary format fixes.

**Comment by binji** [comment]
The cmake branch landed, so this should be fixed.
