### ISSUE TITLE
not working on agianst V8 version 5.1.0 (candidate)

### ISSUE THREAD

**Issue by wanderer** [WebAssembly/sexpr-wasm-prototype#38]
From the example in the Readme
```
var buffer = readbuffer('test.wasm');
var module = _WASMEXP_.instantiateModule(buffer, {});
```

`module` comes out undefined at the end here.  It should export `test`

**Comment by titzer** [comment]
With a recent change, exported functions are now bundled into an "exports" object that hangs off the module returned.

**Comment by wanderer** [comment]
thanks @titzer
