### ISSUE TITLE
Handle new `select` syntax

### ISSUE THREAD

**Issue by jfbastien** [WebAssembly/sexpr-wasm-prototype#39]
sexpr-wasm doesn't handle the new `select` syntax, which @kripken [added to binaryen](https://github.com/WebAssembly/binaryen/commit/14cc71b380005d3b2c5289ebfd20f5bf82ff4c79). This breaks the waterfall.

/cc @dschuff

**Comment by binji** [comment]
Fixed in afb456c314504c3ac1bec24fc4e83d45d92d0015.
