### ISSUE TITLE
Provide a way to get SourceLocations

### ISSUE THREAD

**Issue by dschuff** [WebAssembly/sexpr-wasm-prototype#4]
The spec interpreter reports assertion errors with line numbers from the source. This would be really handy for debugging codegen issues (e.g. in a test suite with hundreds of assertions, which one is failing?). Currently WAOT just tracks and prints the count (i.e. "assertion number X failed") but a line number would be even better. That would have more immediate utility but at some point it might become nice to have line information for expressions too (maybe I want to generate debug info?) That's sort of a speculative use case and may not matter during the time horizon that sexpr-wasm matters, but something that might be nice to have in mind. I'd be happy for asserts for now.
I don't know if it would be better just to hang SourceLocations off of some existing data structure, or pass extra callback args or what, it doesn't matter much to me, I don't think.

**Comment by binji** [comment]
Good idea. I'll add the assert ones for now, but it would be good to have locations for everything, really.

**Comment by binji** [comment]
Fixed in a86003ac1f90e3c23d2ccc3b0bc4fa42fdaada22.

**Comment by binji** [comment]
Actually, I'll leave this open for adding SourceLocations everywhere.

**Comment by binji** [comment]
Really fixed in f82e0c4b481982d6c8c3af79242f3fc9da7e77e8. Not sure if all the locations are great, but they should be usable. Note: this will break all of your callbacks :)
