### ISSUE TITLE
scripts/download-d8.sh seems broken

### ISSUE THREAD

**Issue by wanderer** [WebAssembly/sexpr-wasm-prototype#51]
I get

```
Downloading https://storage.googleapis.com/webassembly/v8-native-prototype/7ee0c81f107ab72d6e46d94e0a1d01be7ae56d34/d8...

curl: (22) The requested URL returned error: 404 Not Found
```

**Comment by binji** [comment]
It uses the currently checked-out v8 submodule SHA to determine what to download. Are you on a local branch?

**Comment by wanderer** [comment]
i'm on master

**Comment by wanderer** [comment]
oh so it should be doing
`https://storage.googleapis.com/webassembly/v8-native-prototype/63f35c26d6fadf8f6a6022f7a82f0701ad9c7a87/d8`

But its getting the current commit for this repo 7ee0c81f107ab72d6e46d94e0a1d01be7ae56d34

**Comment by wanderer** [comment]
i forgot `git submodule update --init`

**Comment by binji** [comment]
Ah, I should probably add a check for that.
