### ISSUE TITLE
br without continue label

### ISSUE THREAD

**Issue by Cellule** [WebAssembly/sexpr-wasm-prototype#53]
the following
`(module (func (loop $a (br $a))) (export "" 0))`
`(module (func (loop $a $b (br $a))) (export "" 0))`
Should generate the same output
However, the first outputs `br 0` (infinite loop) and the second outputs `br 1` (all is good)

**Comment by JSStats** [comment]
Looks ok from what I understood it should be. First case might be clearer as `(module (func (loop $b (br $b))) (export "" 0))` and should loop.

**Comment by Cellule** [comment]
I found this in one of @lukewagner 's test cases. I believe SpiderMonkey consider the 2 modules the same which leads me to believe it is not so clear by spec.

**Comment by JSStats** [comment]
The 'spec' is the official reference and the following loops in the ml-proto wasm:
```
(module
 (func $tst (loop $a (br $a)))
 (export "tst" $tst))
(invoke "tst")
```

If SpiderMonkey is parsing the was text otherwise then perhaps a bug should be filed against it.

**Comment by binji** [comment]
Yes, unfortunately it is not clear from the specification here anymore: https://github.com/WebAssembly/spec/blob/master/ml-proto/README.md#s-expression-syntax

But the correct behavior is `(loop $exit $cont ...)` and `(loop $cont ...)`. A bit odd, but makes sense when you consider that the looping label will be used more often than the exit label.

**Comment by Cellule** [comment]
If this is the correct behavior at this time then I will close this.
I was confused at the time and thought the problem was the tool.
