### ISSUE TITLE
Is there a way to force use of prebuilt wasm-bison-parser.[ch] files?

### ISSUE THREAD

**Issue by mbodart** [WebAssembly/sexpr-wasm-prototype#54]
I have a flavor of bison installed, so the new build procedure tries to use it.
Trouble is, it's an older version and cannot consume wasm-bison-parser.y:

sexpr-wasm-prototype/src/wasm-bison-parser.y:101.20-33: error: syntax error, unexpected {...}
make[2]: *** [wasm-bison-parser.c] Error 1

Is there a way to force use of the prebuilt files?

For example, can cmake check the bison version?

**Comment by binji** [comment]
Ah, yes, I believe so. See https://cmake.org/cmake/help/v3.0/module/FindBISON.html. I'm not sure what the minimum version is, however. My local machine has Bison 3.0.2.

**Comment by mbodart** [comment]
Nice, thanks!

I just changed find_package(BISON) to find_package(BISON 3.0), and it does the trick.
My version is 2.7, but I don't know where the cutoff is.
As using the prebuilt files seems conservatively safe,
a value of 3.0 seems reasonable as a first stab.
It can be easily tweaked.

No urgency to fix as I'm fine with this workaround.
But others may encounter the issue.

**Comment by binji** [comment]
OK, I set the minimum to 3.0.
