### ISSUE TITLE
Whitespace between function name token and left paren

### ISSUE THREAD

**Issue by dschuff** [WebAssembly/sexpr-wasm-prototype#6]
I have a test that generated the following code, and fed it into sexpr-wasm
(module
  (func $foomore(call $foo (i32.const 0x0)) )
  (func $foo (param i32)(nop))
)

Note the lack of space between $foomore and its opening paren. Sometime between rev 64fb062d and rev 7601228b this stopped being accepted by the parser, which now issues the following confusing error:
<filename>:2:23: expected '(', not "$foo"
It looks like the "(call" is getting sucked into the "$foomore" token. 

I don't actually know what the rules of s-expressions are in that case; maybe this is the correct behavior?

**Comment by binji** [comment]
Ah, this is probably a bug I introduced when I started parsing `nan(0x...)`

**Comment by binji** [comment]
Fixed in 4449e0a0d2eedc3e12524c5c65f29a9b1e2b3398.
