### ISSUE TITLE
legacy if

### ISSUE THREAD

**Issue by wanderer** [WebAssembly/sexpr-wasm-prototype#62]
It looks like this prototype is still using the old `if`. For example this
```
    (if
      (i32.const 1)
      (br 0)
     )
```
gets turned into 
```
    (if
      (i32.const 1)
      (block (br 0))
     )
```
[related](https://github.com/WebAssembly/spec/issues/270#issuecomment-203959770)

**Comment by binji** [comment]
This is a temporary issue related to the discrepancy between if as defined in the spec repo and the binary format. It will be resolved when we switch to postorder.
