### ISSUE TITLE
wasm-interp: block-break type crash.

### ISSUE THREAD

**Issue by JSStats** [WebAssembly/sexpr-wasm-prototype#65]
The following is valid wast but crashes in wasm-interp.
```
(module
  (func $tst1
    (block
      (block $l (br $l (i32.const 1)) (nop))
      (nop)))

  (export "tst" $tst1)
)
```

**Comment by binji** [comment]
Hm, I get an arity mismatch in sexpr-wasm and ml-proto when trying to run this. I've actually been working on making a flag to disable type checking in sexpr-wasm so I can more easily catch type checking in wasm-interp. But it would help if you had a binary that demonstrates the crash.
