### ISSUE TITLE
LEB128 question

### ISSUE THREAD

**Issue by wanderer** [WebAssembly/sexpr-wasm-prototype#8]
here is my test code
```
(module
  (func (result i32)
    (i32.add (i32.const 624485) (i32.const 2))))
````
LEB of 624485 [should be 0xE58E26](https://en.wikipedia.org/wiki/LEB128#Unsigned_LEB128)

But from the prototype if get
```
; function 0

....
 
0000014: 0a                                         ; OPCODE_I32_CONST
0000015: 6587 0900                                  ; u32 literal
....
```

how is 0x65870900 derived?

**Comment by binji** [comment]
constant literals are not stored as LEB128, so that is just 624485 in hex (0x98765).

**Comment by wanderer** [comment]
thanks @binji! What is getting encoded in LEB128 then?

**Comment by binji** [comment]
Currently, in the v8-native binary format, just section item counts and indexes. Search for out_leb128 in wasm-gen.c for the full list.

**Comment by wanderer** [comment]
awesome thanks!
